/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscribePendingRouteImport } from './routes/subscribe.pending'
import { Route as SubscribeErrorRouteImport } from './routes/subscribe.error'
import { Route as SubscribeConfirmedRouteImport } from './routes/subscribe.confirmed'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTypesRouteImport } from './routes/_app.types'
import { Route as AppSubscribersRouteImport } from './routes/_app.subscribers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSendRouteImport } from './routes/_app.send'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppComposeRouteImport } from './routes/_app.compose'
import { Route as AppTypesTypeIdRouteImport } from './routes/_app.types.$typeId'
import { Route as AppHistoryCampaignIdRouteImport } from './routes/_app.history.$campaignId'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribePendingRoute = SubscribePendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => SubscribeRoute,
} as any)
const SubscribeErrorRoute = SubscribeErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => SubscribeRoute,
} as any)
const SubscribeConfirmedRoute = SubscribeConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => SubscribeRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTypesRoute = AppTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersRoute = AppSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppTypesTypeIdRoute = AppTypesTypeIdRouteImport.update({
  id: '/$typeId',
  path: '/$typeId',
  getParentRoute: () => AppTypesRoute,
} as any)
const AppHistoryCampaignIdRoute = AppHistoryCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => AppHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/compose': typeof AppComposeRoute
  '/help': typeof AppHelpRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/subscribers': typeof AppSubscribersRoute
  '/types': typeof AppTypesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/subscribe/confirmed': typeof SubscribeConfirmedRoute
  '/subscribe/error': typeof SubscribeErrorRoute
  '/subscribe/pending': typeof SubscribePendingRoute
  '/history/$campaignId': typeof AppHistoryCampaignIdRoute
  '/types/$typeId': typeof AppTypesTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/compose': typeof AppComposeRoute
  '/help': typeof AppHelpRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/subscribers': typeof AppSubscribersRoute
  '/types': typeof AppTypesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/subscribe/confirmed': typeof SubscribeConfirmedRoute
  '/subscribe/error': typeof SubscribeErrorRoute
  '/subscribe/pending': typeof SubscribePendingRoute
  '/history/$campaignId': typeof AppHistoryCampaignIdRoute
  '/types/$typeId': typeof AppTypesTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/subscribe': typeof SubscribeRouteWithChildren
  '/_app/compose': typeof AppComposeRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/history': typeof AppHistoryRouteWithChildren
  '/_app/send': typeof AppSendRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscribers': typeof AppSubscribersRoute
  '/_app/types': typeof AppTypesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/subscribe/confirmed': typeof SubscribeConfirmedRoute
  '/subscribe/error': typeof SubscribeErrorRoute
  '/subscribe/pending': typeof SubscribePendingRoute
  '/_app/history/$campaignId': typeof AppHistoryCampaignIdRoute
  '/_app/types/$typeId': typeof AppTypesTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscribe'
    | '/compose'
    | '/help'
    | '/history'
    | '/send'
    | '/settings'
    | '/subscribers'
    | '/types'
    | '/auth/callback'
    | '/subscribe/confirmed'
    | '/subscribe/error'
    | '/subscribe/pending'
    | '/history/$campaignId'
    | '/types/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscribe'
    | '/compose'
    | '/help'
    | '/history'
    | '/send'
    | '/settings'
    | '/subscribers'
    | '/types'
    | '/auth/callback'
    | '/subscribe/confirmed'
    | '/subscribe/error'
    | '/subscribe/pending'
    | '/history/$campaignId'
    | '/types/$typeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/subscribe'
    | '/_app/compose'
    | '/_app/help'
    | '/_app/history'
    | '/_app/send'
    | '/_app/settings'
    | '/_app/subscribers'
    | '/_app/types'
    | '/auth/callback'
    | '/subscribe/confirmed'
    | '/subscribe/error'
    | '/subscribe/pending'
    | '/_app/history/$campaignId'
    | '/_app/types/$typeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SubscribeRoute: typeof SubscribeRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/pending': {
      id: '/subscribe/pending'
      path: '/pending'
      fullPath: '/subscribe/pending'
      preLoaderRoute: typeof SubscribePendingRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/subscribe/error': {
      id: '/subscribe/error'
      path: '/error'
      fullPath: '/subscribe/error'
      preLoaderRoute: typeof SubscribeErrorRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/subscribe/confirmed': {
      id: '/subscribe/confirmed'
      path: '/confirmed'
      fullPath: '/subscribe/confirmed'
      preLoaderRoute: typeof SubscribeConfirmedRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/types': {
      id: '/_app/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof AppTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers': {
      id: '/_app/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AppSubscribersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/types/$typeId': {
      id: '/_app/types/$typeId'
      path: '/$typeId'
      fullPath: '/types/$typeId'
      preLoaderRoute: typeof AppTypesTypeIdRouteImport
      parentRoute: typeof AppTypesRoute
    }
    '/_app/history/$campaignId': {
      id: '/_app/history/$campaignId'
      path: '/$campaignId'
      fullPath: '/history/$campaignId'
      preLoaderRoute: typeof AppHistoryCampaignIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryCampaignIdRoute: typeof AppHistoryCampaignIdRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryCampaignIdRoute: AppHistoryCampaignIdRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppTypesRouteChildren {
  AppTypesTypeIdRoute: typeof AppTypesTypeIdRoute
}

const AppTypesRouteChildren: AppTypesRouteChildren = {
  AppTypesTypeIdRoute: AppTypesTypeIdRoute,
}

const AppTypesRouteWithChildren = AppTypesRoute._addFileChildren(
  AppTypesRouteChildren,
)

interface AppRouteChildren {
  AppComposeRoute: typeof AppComposeRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppSendRoute: typeof AppSendRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscribersRoute: typeof AppSubscribersRoute
  AppTypesRoute: typeof AppTypesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppComposeRoute: AppComposeRoute,
  AppHelpRoute: AppHelpRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppSendRoute: AppSendRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscribersRoute: AppSubscribersRoute,
  AppTypesRoute: AppTypesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SubscribeRouteChildren {
  SubscribeConfirmedRoute: typeof SubscribeConfirmedRoute
  SubscribeErrorRoute: typeof SubscribeErrorRoute
  SubscribePendingRoute: typeof SubscribePendingRoute
}

const SubscribeRouteChildren: SubscribeRouteChildren = {
  SubscribeConfirmedRoute: SubscribeConfirmedRoute,
  SubscribeErrorRoute: SubscribeErrorRoute,
  SubscribePendingRoute: SubscribePendingRoute,
}

const SubscribeRouteWithChildren = SubscribeRoute._addFileChildren(
  SubscribeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SubscribeRoute: SubscribeRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
